version: 2
updates:
  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: weekly
    open-pull-requests-limit: 10

  - package-ecosystem: npm
    directory: "/npm-packages"
    schedule:
      interval: weekly
    open-pull-requests-limit: 10

  - package-ecosystem: npm
    directory: "/npm-packages/packages/mnp"
    schedule:
      interval: weekly

  - package-ecosystem: npm
    directory: "/npm-packages/packages/mnp-material"
    schedule:
      interval: weekly

  - package-ecosystem: npm
    directory: "/npm-packages/packages/mnp-mie"
    schedule:
      interval: weekly
