{application,hex_core,
             [{description,"Reference implementation of Hex specifications"},
              {vsn,"0.12.2"},
              {registered,[]},
              {applications,[kernel,stdlib,inets,ssl]},
              {licenses,["Apache-2.0"]},
              {include_paths,["CHANGELOG.md"]},
              {exclude_paths,["src/safe_erl_term.erl"]},
              {links,[{"GitHub","https://github.com/hexpm/hex_core"},
                      {"Hex specifications",
                       "https://github.com/hexpm/specifications"}]},
              {doc,"doc"},
              {modules,[hex_api,hex_api_auth,hex_api_key,hex_api_oauth,
                        hex_api_organization,hex_api_organization_member,
                        hex_api_package,hex_api_package_owner,hex_api_release,
                        hex_api_short_url,hex_api_user,hex_core,hex_erl_tar,
                        hex_filename,hex_http,hex_http_httpc,hex_licenses,
                        hex_pb_names,hex_pb_package,hex_pb_signed,
                        hex_pb_versions,hex_registry,hex_repo,
                        hex_safe_binary_to_term,hex_tarball,safe_erl_term]}]}.
