name: R CRAN Check

on:
  push:
    paths:
      - "r-mnp-plasmon/**"
      - ".github/workflows/r-cran-check.yml"
  workflow_dispatch:

permissions:
  contents: read

jobs:
  check-r-package:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup R
        uses: r-lib/actions/setup-r@v2

      - name: Install dependencies
        uses: r-lib/actions/setup-r-dependencies@v2
        with:
          extra-packages: any::rcmdcheck

      - name: R CMD check
        run: |
          Rscript -e "rcmdcheck::rcmdcheck('r-mnp-plasmon', args = '--no-manual', error_on = 'warning')"

      - name: Build source tarball
        run: |
          R CMD build r-mnp-plasmon

      - name: Upload source tarball artifact
        uses: actions/upload-artifact@v4
        with:
          name: r-mnp-plasmon-source
          path: mnpPlasmonR_*.tar.gz
