name: TagBot

on:
  issue_comment:
    types: [created]
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

permissions:
  actions: read
  checks: read
  contents: write
  deployments: read
  issues: read
  packages: read
  pages: read
  pull-requests: read
  repository-projects: read
  security-events: read
  statuses: read

jobs:
  TagBot:
    if: github.event_name == 'workflow_dispatch' || github.actor == 'JuliaTagBot' || (github.event_name == 'issue_comment' && startsWith(github.event.comment.body, '@JuliaRegistrator'))
    runs-on: ubuntu-latest
    steps:
      - uses: JuliaRegistries/TagBot@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          subdir: julia-mnp-plasmon
